// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Direction } from "./../Types.sol";

interface IPlayerSystem {
  function spawn(int32 x, int32 y) external;

  function kill() external;

  function move(Direction dir) external;

  function getPlayerSpeed(bytes32) external pure returns (uint32);

  function beginTravel(int32 x, int32 y) external;

  function endTravel() external;
}
